runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: production
  PINTEREST_CLIENT_ID: 1508548
  PINTEREST_CLIENT_SECRET: 1e4910ff2b56f8021e4b28b392ac145975bbfc60
  PINTEREST_REDIRECT_URI: http://localhost:5001/auth/pinterest/callback
  GOOGLE_APPLICATION_CREDENTIALS: ./final-project-458022-2a7dc1643189.json
  GOOGLE_VISION_API_KEY: AIzaSyBIqpw7MqKCQkkBFWldYMzBkUCkuIoPMiw
  GEMINI_API_KEY: AIzaSyB3X0yylmYu5NpjlvSmMW0PlYEOnseU0NM
  SPOTIFY_CLIENT_ID: de9165a6898744e0b473335cfecfd41f
  SPOTIFY_CLIENT_SECRET: b0f0d8c85dc04e7cb4030a2dd48079dc
