steps:
  # Step 1: Set up Node.js environment and install dependencies
  - name: "node:20" # Use the official Node.js image (adjust version as needed)
    id: Install dependencies
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install

  # Step 2: Start the backend application using `npm run start`
  - name: "node:20" # Use the same Node.js image
    id: Start backend
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm run start

timeout: "900s" # Optional, adjust if needed for your build time
